# AROS Build pipeline
# Builds a single target defined in the pipeline variables.
# set -:
#    arosbuild.name
#    arosbuild.target
#    arosbuild.variant
#    arosbuild.package  - "system" "boot-iso"
#    arosbuild.packagefmt - "lha" "zip" "tar.bz2"
#

trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 240
  pool:
    vmImage: '$(arosbuild.vmimage)'

  variables:
    AROSBUILDGCCVERS: '9.1.0'
    AROSBUILDTOOLCHAINDIR:  '$(AZBUILDPATH)/toolchain' # Location toolchains are installed in
    AROSPORTSSRCSDIR:  '$(AZBUILDPATH)/portssources' # Location external sources are downloaded to.
    AROSBUILDSDIR:  '$(AZBUILDPATH)/builds' # Location builds are done in
    AROSLOGSDIR:  '$(AZBUILDPATH)/logs' # Location logs are stored in.
    AROSDISTFILESDIR:  '$(AZBUILDPATH)/distfiles' # Location built binaries are copied to.
    AZBUILDPATH: '$(Build.BinariesDirectory)' # workspace path
    AROSBUILDDIR:  '$(AROSBUILDSDIR)/$(arosbuild.name)' # current builds directory
    AROSSRCDIR: '$(system.defaultWorkingDirectory)' # Path to the source code
    AROSCONTRIBSRCDIR: '$(Agent.BuildDirectory)/s-contrib' # Path to the contrib source code

  steps:
  - script: |
      CONFIGOPTS="--target=$(arosbuild.target)"
      if [ "$AROSBUILD_VARIANT" != "" ]; then
        CONFIGOPTS="$CONFIGOPTS --enable-target-variant=$(arosbuild.variant)"
      fi
      sudo apt-key adv --keyserver packages.microsoft.com --recv-keys B02C46DF417A0893
      sudo apt-get update -y
      sudo apt-get upgrade -y
      sudo apt-get install -y libpng-dev zlib1g-dev libxcursor-dev libgl1-mesa-dev libasound2-dev
      sudo apt-get install -y gawk bison flex netpbm automake cmake genisoimage sshpass
      sudo apt-get install -y python-mako libswitch-perl gperf gcc-multilib g++ ccache
      sudo apt-get install -y jlha-utils wget
      if [ "$AROSBUILD_TARGET" = "mingw32-i386" ]; then
        sudo apt-get install -y mingw-w64-i686-dev gcc-mingw-w64-i686 g++-mingw-w64-i686 mingw-w64-tools
        CONFIGOPTS="$CONFIGOPTS --with-kernel-toolchain-prefix=i686-w64-mingw32-"
      fi
      CONFIGOPTS="$CONFIGOPTS --enable-ccache --with-gcc-version=$(AROSBUILDGCCVERS) --enable-build-type=nightly --with-portssources=$(AROSPORTSSRCSDIR)"
      echo "##vso[task.setvariable variable=AROSCONFIGOPTIONS]$CONFIGOPTS"
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: 'Installing AROS build dependencies for Ubuntu'

  - script: |
      CONFIGOPTS="--target=$(arosbuild.target)"
      if [ "$AROSBUILD_VARIANT" != "" ]; then
        CONFIGOPTS="$CONFIGOPTS --enable-target-variant=$(arosbuild.variant)"
      fi
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
      brew list gawk &>/dev/null || brew install gawk
      brew list gnu-sed &>/dev/null || brew install gnu-sed
      brew list autoconf &>/dev/null || brew install autoconf
      brew list automake &>/dev/null || brew install automake
      brew list wget &>/dev/null || brew install wget
      brew list cmake &>/dev/null || brew install cmake
      brew list netpbm &>/dev/null || brew install netpbm
      CONFIGOPTS="$CONFIGOPTS --enable-ccache --with-gcc-version=$(AROSBUILDGCCVERS) --enable-build-type=nightly --with-portssources=$(AROSPORTSSRCSDIR)"
      echo "##vso[task.setvariable variable=AROSCONFIGOPTIONS]$CONFIGOPTS"
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: 'Installing AROS build dependencies for MacOS'

  - script: |
      mkdir -p '$(AROSCONTRIBSRCDIR)'
      echo '##vso[task.prependpath]$(AROSCONTRIBSRCDIR)'
      git clone --depth 1 https://github.com/aros-development-team/contrib.git $(AROSCONTRIBSRCDIR)/
      mkdir -p '$(AROSBUILDSDIR)'
      mkdir -p '$(AROSBUILDTOOLCHAINDIR)'
      mkdir -p '$(AROSPORTSSRCSDIR)'
      mkdir -p '$(AROSLOGSDIR)'
      echo '##vso[task.prependpath]$(AROSBUILDTOOLCHAINDIR)'
      echo '##vso[task.prependpath]$(AROSBUILDSDIR)'
      echo '##vso[task.prependpath]$(AROSPORTSSRCSDIR)'
      echo '##vso[task.prependpath]$(AROSLOGSDIR)'
      BUILDDATE=$(date -u +'%Y%m%d')
      echo "##vso[task.setvariable variable=arosbuilddate]$BUILDDATE"
      echo "##vso[task.setvariable variable=arosbuildid]AROS-$BUILDDATE"
      echo "##vso[task.setvariable variable=AROSPACKAGEDIR]$(AROSBUILDSDIR)/AROS-$BUILDDATE-$(arosbuild.name)-$(arosbuild.package)"
      echo "Common BUILD dir '$(AROSBUILDSDIR)'"
      echo "Common TOOLCHAIN dir '$(AROSBUILDTOOLCHAINDIR)'"
      echo "Common PORTSSOURCES dir '$(AROSPORTSSRCSDIR)'"
      echo "Common LOG dir '$(AROSLOGSDIR)'"
    displayName: 'Setup common workspace'

  - script: |
      mkdir -p '$(AROSBUILDSDIR)/$(AROSBUILDID)-source'
      cp -r $(AROSSRCDIR)/* $(AROSBUILDSDIR)/$(AROSBUILDID)-source/
      echo "Creating $(AROSBUILDID)-source.tar.bz2"
      tar cjvf $(AROSBUILDID)-source.tar.bz2 --exclude=.git $(AROSBUILDID)-source
      md5sum $(AROSBUILDID)-source.tar.bz2 >$(AROSBUILDID)-source.tar.bz2.md5
      rm -Rf $(AROSBUILDSDIR)/$(AROSBUILDID)-source
    workingDirectory: '$(AROSBUILDSDIR)'
    displayName: 'Creating AROS source package'

  - script: |
      mkdir -p '$(AROSBUILDSDIR)/$(AROSBUILDID)-contrib-source'
      cp -r $(AROSCONTRIBSRCDIR)/* $(AROSBUILDSDIR)/$(AROSBUILDID)-contrib-source/
      echo "Creating $(AROSBUILDID)-source.tar.bz2"
      tar cjvf $(AROSBUILDID)-contrib-source.tar.bz2 --exclude=.git $(AROSBUILDID)-contrib-source
      md5sum $(AROSBUILDID)-contrib-source.tar.bz2 >$(AROSBUILDID)-contrib-source.tar.bz2.md5
      rm -Rf $(AROSBUILDSDIR)/$(AROSBUILDID)-contrib-source
    workingDirectory: '$(AROSBUILDSDIR)'
    displayName: 'Creating contrib source package'

  - script: |
      mkdir -p ~/.ssh
      mkdir -p '$(Build.BinariesDirectory)/Upload/$(arosbuilddate)/Sources'
      cp $(AROSBUILDSDIR)/$(AROSBUILDID)-*source.tar.bz2 $(Build.BinariesDirectory)/Upload/$(arosbuilddate)/Sources/
      cp $(AROSBUILDSDIR)/$(AROSBUILDID)-*source.tar.bz2.md5 $(Build.BinariesDirectory)/Upload/$(arosbuilddate)/Sources/
      ssh-keyscan -t rsa web.sourceforge.net >> ~/.ssh/known_hosts
      sshpass -p "$MAPPED_PASS" rsync -avz --rsh=ssh $(Build.BinariesDirectory)/Upload/ $MAPPED_USER,aros@web.sourceforge.net:uploads/nightly2/
      rm -Rf $(Build.BinariesDirectory)/Upload/$(arosbuilddate)/Sources
    env:
      MAPPED_USER: $(SF_RSYNC_USER)
      MAPPED_PASS: $(SF_RSYNC_PASSWORD)
    displayName: 'Deploying source package(s)'

  - script: |
      mkdir -p '$(AROSBUILDDIR)'
      mkdir -p '$(AROSPACKAGEDIR)'
      echo '##vso[task.prependpath]$(AROSBUILDDIR)'
      echo '##vso[task.prependpath]$(AROSPACKAGEDIR)'
      echo "Target BUILD dir '$(AROSBUILDDIR)'"
      echo "Target PACKAGE dir '$(AROSPACKAGEDIR)'"
    displayName: 'Setup $(arosbuild.name) workspace'

  - script: |
      function execute {
        {
          echo '>>>' $*
          $*
          if [ $? != 0 ]; then
            touch /tmp/_aros_build_failed
          fi
        } 2>&1 | tee -a $(AROSLOGSDIR)/$(arosbuild.package)-$(arosbuild.name).log
        if [ -f /tmp/_aros_build_failed ]; then
          exit 5
        fi
      }
      execute $(AROSSRCDIR)/configure $(AROSCONFIGOPTIONS)
    workingDirectory: '$(AROSBUILDDIR)'
    displayName: 'Configuring $(arosbuild.name)'

  - script: |
      function execute {
        {
          echo '>>>' $*
          $*
          if [ $? != 0 ]; then
            touch /tmp/_aros_build_failed
          fi
        } 2>&1 | tee -a $(AROSLOGSDIR)/$(arosbuild.package)-$(arosbuild.name).log
        if [ -f /tmp/_aros_build_failed ]; then
          exit 5
        fi
      }
      execute make -j 2
    workingDirectory: '$(AROSBUILDDIR)'
    displayName: 'Build $(arosbuild.name) core system'

  - script: |
      function execute {
        {
          echo '>>>' $*
          $*
          if [ $? != 0 ]; then
            touch /tmp/_aros_build_failed
          fi
        } 2>&1 | tee -a $(AROSLOGSDIR)/$(arosbuild.package)-$(arosbuild.name).log
      }
      execute make -j 2 boot-distfiles
      if [ -f /tmp/_aros_build_failed ]; then
        touch /tmp/_aros_boot_build_failed
        rm /tmp/_aros_build_failed
      else
        if [ -d "$(AROSBUILDDIR)/distfiles" ]; then 
          mv distfiles distfiles-boot
        fi
      fi
    workingDirectory: '$(AROSBUILDDIR)'
    displayName: 'Build $(arosbuild.name) boot distfiles'

  - script: |
      function execute {
        {
          echo '>>>' $*
          $*
          if [ $? != 0 ]; then
            touch /tmp/_aros_build_failed
          fi
        } 2>&1 | tee -a $(AROSLOGSDIR)/$(arosbuild.package)-$(arosbuild.name).log
      }
      execute make -j 2 distfiles
      if [ -f /tmp/_aros_build_failed ]; then
        touch /tmp/_aros_distfiles_build_failed
        rm /tmp/_aros_build_failed
        rm -Rf $(AROSBUILDDIR)/distfiles
      fi
    workingDirectory: '$(AROSBUILDDIR)'
    displayName: 'Build $(arosbuild.name) main distfiles'


  - script: |
      function execute {
        {
          echo '>>>' $*
          $*
          if [ $? != 0 ]; then
            touch /tmp/_aros_build_failed
          fi
        } 2>&1 | tee -a $(AROSLOGSDIR)/$(arosbuild.package)-$(arosbuild.name).log
      }
      mv $(AROSCONTRIBSRCDIR) $(AROSSRCDIR)/contrib
      execute make -j 2 contrib
      mv $(AROSSRCDIR)/contrib $(AROSCONTRIBSRCDIR)
      if [ -f /tmp/_aros_build_failed ]; then
        touch /tmp/_aros_contrib_build_failed
        rm /tmp/_aros_build_failed
        rm -Rf 
      fi
    workingDirectory: '$(AROSBUILDDIR)'
    condition: eq( variables['arosbuild.withcontrib'], 'yes' )
    displayName: 'Build $(arosbuild.name) contrib'

  - script: |
      if [ -d "$(AROSBUILDDIR)/distfiles-boot" ]; then
        if [ ! -f /tmp/_aros_boot_build_failed ]; then
          mkdir -p '$(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage)'
          cp -r $(AROSBUILDDIR)/distfiles-boot/* $(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage)/
          cp -r $(AROSSRCDIR)/LICENSE $(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage)/
          cp -r $(AROSSRCDIR)/ACKNOWLEDGEMENTS $(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage)/
         echo "Creating $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage).$(arosbuild.bootpackagefmt)"
          if [[ "$(arosbuild.bootpackagefmt)" = "zip" ]]
          then
            zip -r9 $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage).$(arosbuild.bootpackagefmt) $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage)
          else
            if [[ "$(arosbuild.bootpackagefmt)" = "tar.bz2" ]]
            then
              tar cjvf $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage).$(arosbuild.bootpackagefmt) $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage)
            else
              if [[ "$(arosbuild.bootpackagefmt)" = "lha" ]]
              then
                lha -a $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage).$(arosbuild.bootpackagefmt) $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage)
              fi
            fi
          fi
          md5sum $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage).$(arosbuild.bootpackagefmt) >$(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage).$(arosbuild.bootpackagefmt).md5
          rm -Rf '$(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.bootpackage)'
        fi
      fi
      if [ ! -f /tmp/_aros_distfiles_build_failed ]; then
        cp -r $(AROSBUILDDIR)/distfiles/* $(AROSPACKAGEDIR)/
        cp -r $(AROSSRCDIR)/LICENSE $(AROSPACKAGEDIR)/
        cp -r $(AROSSRCDIR)/ACKNOWLEDGEMENTS $(AROSPACKAGEDIR)/
        echo "Creating $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.package).$(arosbuild.packagefmt)"
        if [[ "$(arosbuild.packagefmt)" = "zip" ]]
        then
          zip -r9 $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.package).$(arosbuild.packagefmt) $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.package)
        else
          if [[ "$(arosbuild.packagefmt)" = "tar.bz2" ]]
          then
            tar cjvf $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.package).$(arosbuild.packagefmt) $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.package)
          else
            if [[ "$(arosbuild.packagefmt)" = "lha" ]]
            then
              lha -a $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.package).$(arosbuild.packagefmt) $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.package)
            fi
          fi
        fi
        md5sum $(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.package).$(arosbuild.packagefmt) >$(AROSBUILDID)-$(arosbuild.name)-$(arosbuild.package).$(arosbuild.packagefmt).md5
      fi
      if [ "$AROSBUILD_WITHCONTRIB" = "yes" ]; then
        if [ ! -f /tmp/_aros_contrib_build_failed ]; then
          mkdir -p '$(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-contrib'
          cp -r $(AROSBUILDDIR)/bin/$(arosbuild.name)/AROS/Extras/* $(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-contrib/
          cp -r $(AROSSRCDIR)/LICENSE $(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-contrib/
          cp -r $(AROSSRCDIR)/ACKNOWLEDGEMENTS $(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-contrib/
          tar cjvf $(AROSBUILDID)-$(arosbuild.name)-contrib.tar.bz2 $(AROSBUILDID)-$(arosbuild.name)-contrib
          md5sum $(AROSBUILDID)-$(arosbuild.name)-contrib.tar.bz2 >$(AROSBUILDID)-$(arosbuild.name)-contrib.tar.bz2.md5
        fi
      fi
      cd $(AROSLOGSDIR)
      bzip2 $(arosbuild.package)-$(arosbuild.name).log
      md5sum $(arosbuild.package)-$(arosbuild.name).log.bz2 >$(arosbuild.package)-$(arosbuild.name).log.bz2.md5
      rm -Rf $(AROSPACKAGEDIR)
    workingDirectory: '$(AROSBUILDSDIR)'
    displayName: 'Creating $(arosbuild.name) package(s)'

  - script: |
      mkdir -p ~/.ssh
      mkdir -p '$(Build.BinariesDirectory)/Upload/$(arosbuilddate)/Binaries'
      mkdir -p '$(Build.BinariesDirectory)/Upload/$(arosbuilddate)/logs/azure'
      cp $(AROSBUILDSDIR)/$(AROSBUILDID)-$(arosbuild.name)-* $(Build.BinariesDirectory)/Upload/$(arosbuilddate)/Binaries/
      cp $(AROSLOGSDIR)/$(arosbuild.package)-$(arosbuild.name).log.bz2 $(Build.BinariesDirectory)/Upload/$(arosbuilddate)/logs/azure/
      cp $(AROSLOGSDIR)/$(arosbuild.package)-$(arosbuild.name).log.bz2.md5 $(Build.BinariesDirectory)/Upload/$(arosbuilddate)/logs/azure/
      ssh-keyscan -t rsa web.sourceforge.net >> ~/.ssh/known_hosts
      sshpass -p "$MAPPED_PASS" rsync -avz --rsh=ssh $(Build.BinariesDirectory)/Upload/ $MAPPED_USER,aros@web.sourceforge.net:uploads/nightly2/
    env:
      MAPPED_USER: $(SF_RSYNC_USER)
      MAPPED_PASS: $(SF_RSYNC_PASSWORD)
    displayName: 'Deploying build'
